name: Deploy to S3 with Quarto

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Check out repository
      uses: actions/checkout@v4

    # 2. Set up Docker container with Quarto
    - name: Set up Docker
      run: |
        docker run -d --name quarto-container -v $(pwd):/project ghcr.io/quarto-dev/quarto:latest tail -f /dev/null

    # 3. Render the Quarto project
    - name: Render Quarto project
      run: |
        docker exec quarto-container quarto render /project
        ls -l $(pwd)/_site

    # 4. Setup MinIO client
    - name: Install AWS CLI
      uses: lovellfelix/minio-deploy-action@v1
      with:
        endpoint: https://s3.embl.de/
        access_key: Ti7WUzZXlGoyNaG6sXh4
        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
        bucket: 'test-bucket-1'
        # Optional inputs with their defaults:
        source_dir: '_site'
        target_dir: '/quarto-example/'

    # 7. Clean up Docker container
    - name: Clean up Docker container
      run: |
        docker stop quarto-container
        docker rm quarto-container
